### ISSUE TITLE
Monitoring Tag with this wrapper

### ISSUE THREAD

**Issue by fuixx217** [sergeymaysak/wirelesstagpy#8]
I'm guessing it isn't possible, but it would be nice to try and have a way to use the data that a tag uses as part of its monitoring functionality.  I have wifi switches on my home network, and I have a tag in my fireplace room.  I would love to turn that switch on or off based on the temperature in the room (to turn on thru-wall fans to circulate the warm air out of the fireplace room).  Currently, I have a monitor set up on a tag to send an email, and I use other python code to read that email account looking for new alerts with the desired subject.  It seems like the https://my.wirelesstag.net/ethClient.asmx?op=GetTagList2 will read from the data that is published, and seemingly rolled up by wirelesstag.net on some interval (I tested updating the temp data on a specific tag, and it did not seem to immediately show up in the call to load_tags(), which appears to be reading from GetTagList2 from what I could deduce.  From what you know, _should_ that be a direct hit to the tag at the time load_tags() is executed?  Thanks for the effort put into this module thus far, very cool stuff!

wirelesstag.net API documentation is severely lacking on the example side of things.

**Comment by nextbots** [comment]
Hi @fuixx217! Well, imagine situation that your code does polling of load_tags every 2 seconds (just because you wrote such code, for example) and each such request would hit real tag or even set of tags to perform immediate reading of temperature sensor from tag. How long battery inside tags would last after such polling? Probably just several hours instead of 1, 1.5 or even 2 years of expected operation. especially it is important for tags with non-replaceable batteries like water leaks sensors.
Another point is that basically interval of polling is defined by end user for each tag and that is your as end user choice on tradeoff between battery life and frequency of readings of sensors data from tag - the minimal you can set is 10 seconds which I believe for temperature is really overkill and has not much sense - usually temperature of air does not change immediately and has inertia to change and interval of readings say from 2 to 10 minutes is very reasonable.

So load_tags respects reading internal set by end users from this prospective. You as user is free to change it for your tags - load_tags will follow. Also from top of my head - I do caching of data retrieved from remote server and do request again only if reading interval specified by end user is greater then last time of last request... This is done to avoid unnecessary network traffic which will get just the same data which is already in cache...

Hope this helps...

**Comment by fuixx217** [comment]
I appreciate the quick reply!  I would guess what I saw then was an issue of the polling interval not being wide enough between times that I sampled.  I ran the script, then within 30 seconds issued an update on my tag, and then re-ran the script, and noticed that the data point didn't change.  The tag, by what I have set, is updating data every 3 hours, so I'll guess, from what you said, the cached data likely wouldn't update again until the pull date/time is beyond the 3 hours like it is set on the tag.  Thanks again for the reply and giving me that detail.
